name: Build and Push to ACR
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:

      - name: install docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          docker build -t $ACR_SERVER/fitnessapp:latest .
          docker push $ACR_SERVER/fitnessapp:latest
